# This is a basic workflow to help you get started with Actions
name: BuildAndPushContainer

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: ingrsvc
  REGISTRY: fupas-cr
  REGISTRY_HOSTNAME: eu.gcr.io
  GITHUB_SHA: ${{ github.sha }}
  SERVICE_NAME: ingrsvc
  SERVICEDIR: "cmd/ingress"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - uses: actions/checkout@v2

    - name: Get dependencies
      run: cd ${{ SERVICEDIR }} && go get -v -t -d ./...

    - name: Build go code
      run: |
        cd ${{ SERVICEDIR }} && go build -o ../../build/${{ SERVICE_NAME }} main.go
        pwd
        ls -la
        ls -la build
    # Setup gcloud CLI
#    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#      with:
#        version: '270.0.0'
#        service_account_email: ${{ secrets.GCP_EMAIL }}
#        service_account_key: ${{ secrets.GCP_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
#    - run: gcloud auth configure-docker    

#    - name: Build the container
#      run: |        
#        docker build -t "$REGISTRY_HOSTNAME"/"$REGISTRY"/"$IMAGE_NAME":"$GITHUB_SHA" \
#          --build-arg GITHUB_SHA="$GITHUB_SHA" \
#          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the docker image to Google Container Registry
#    - name: Publish the container
#      run: |
#        docker push $REGISTRY_HOSTNAME/$REGISTRY/$IMAGE_NAME:$GITHUB_SHA
#        docker tag $REGISTRY_HOSTNAME/$REGISTRY/$IMAGE_NAME:$GITHUB_SHA $REGISTRY_HOSTNAME/$REGISTRY/$IMAGE_NAME:latest
#        docker push $REGISTRY_HOSTNAME/$REGISTRY/$IMAGE_NAME:latest
