# This is a basic workflow to help you get started with Actions
name: BuildAndPushContainer

on:
  push:
    branches: [ release ]

env:
  GITHUB_SHA: ${{ github.sha }}
  GOARCH: amd64
  GOOS: linux
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/checkout@v2

    - name: Get dependencies
      run: cd cmd/router && go get -v -t -d ./...

    - name: Build go code
      run: |
        cd cmd/router && go build -o ../../build/router main.go

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build/router
        destination: fupas-bin
